const alfabetos = {
    "Albanés Caucásico": [10530, 10563],
    "Alemán": [0041,
        0061,
        0042,
        0062,
        0043,
        0063,
        0044,
        0064,
        0045,
        0065,
        0046,
        0066,
        0047,
        0067,
        0048,
        0068,
        0049,
        0069,
        004A,
        006A,
        004B,
        006B,
        004C,
        006C,
        004D,
        006D,
        004E,
        006E,
        004F,
        006F,
        0050,
        0070,
        0051,
        0071,
        0052,
        0072,
        0053,
        0073,
        0054,
        0074,
        0055,
        0075,
        0056,
        0076,
        0057,
        0077,
        0058,
        0078,
        0059,
        0079,
        005A,
        007A,
        00C4,
        00E4,
        00D6,
        00F6,
        00DC,
        00FC,
            1E9E,
        00DF],
    "Árabe de Norte Antiguo": [],
    "Arameo Imperial": [],
    "Armenio": [],
    "Avestano": [],
    "Balinés": [],
    "Bamum": [],
    "Baskir": [],
    "Bassa-vah": [],
    "Batak": [],
    "Bengalí": [],
    "Bielorruso": [],
    "Bopomofo. Zhuyin": [],
    "Brahmi": [],
    "Bugino": [],
    "Buhid": [],
    "Búlgaro": [],
    "Cario": [],
    "Chakma": [],
    "Cham": [],
    "Checo": [],
    "Cherokee": [],
    "Chino Pinyin": [],
    "Chiprioto Silabario": [],
    "Cirílico": [],
    "Copto": [],
    "Deseret": [],
    "Devanagari": [],
    "Elbasan": [],
    "Español": [],
    "Esperanto": [],
    "Etrusco Antiguo Cursivo": [],
    "Fenicio": [],
    "Fonético Internacional": [],
    "Francés": [],
    "Georgiano": [],
    "Geʻez Etíope": [],
    "Glagolitico": [],
    "Grantha": [],
    "Griego": [],
    "Gujarati": [],
    "Gurmukhi": [],
    "Gótico": [],
    "Hangul": [],
    "Hanunoo": [],
    "Hebreo": [],
    "Hiragana Japonés": [],
    "Húngaro": [],
    "Inglés": [],
    "Italiano": [],
    "Japonés Katakana": [],
    "Javanés": [],
    "Kaithi": [],
    "Kannada": [],
    "Kayah Li": [],
    "Kazajo": [],
    "Kharoshthi": [],
    "Khmer": [],
    "Khojki": [],
    "Khudawadi": [],
    "Lao": [],
    "Latino": [],
    "Lepcha": [],
    "Liciano": [],
    "Lidia": [],
    "Limbu": [],
    "Lineal B Silabario": [],
    "Lisu": [],
    "Mahajani": [],
    "Malayalam": [],
    "Mandaico": [],
    "Maniquea": [],
    "Meetei Mayek": [],
    "Mende Kikakui": [],
    "Meroitico Cursivo": [],
    "Modi": [],
    "Mongol": [],
    "Mro": [],
    "Myanmar": [],
    "Nabateo": [],
    "Nko": [],
    "Nuevo Tai Lue": [],
    "Ogham": [],
    "Ol Chiki": [],
    "Oriya": [],
    "Osmanya": [],
    "Pahawh Hmong": [],
    "Pahlavi": [],
    "Palmyrene": [],
    "Pau Cin Hau": [],
    "Permico Antiguo": [],
    "Perso Antiguo": [],
    "Phags-pa": [],
    "Polaco": [],
    "Pollard": [],
    "Rejang": [],
    "Ruso": [],
    "Rúnico": [],
    "Samaritano": [],
    "Saurashtra": [],
    "Sharada": [],
    "Shavian": [],
    "Siddham": [],
    "Silabario Aborigen Canadiense Unificado": [],
    "Silabario Vai": [],
    "Sinhala": [],
    "Siríaco": [],
    "Sora Sompeng": [],
    "Sundanés": [],
    "Syloti Nagri": [],
    "Tagalo": [],
    "Tagbanwa": [],
    "Tai Le": [],
    "Tai Tham": [],
    "Tai Vietnam": [],
    "Tailandés": [],
    "Takri": [],
    "Tamil": [],
    "Telugu": [],
    "Thaana": [],
    "Tibetano": [],
    "Tifinagh": [],
    "Tirhuta": [],
    "Turco": [],
    "Turco Rúnico Antiguo": [],
    "Tártaro": [],
    "Ucraniano": [],
    "Ugaritico": [],
    "Varang Kshiti": [],
    "Yi Silabario": [],
    "Árabe": [],
    "Árabe de Sur Antiguo": []
};